### ISSUE TITLE
Register in General

### ISSUE THREAD

**Issue by mpf** [MPF-Optimization-Laboratory/ActiveSetPursuit.jl#15]
@JuliaRegistrator register()

**Comment by mpf** [comment]
@JuliaRegistrator register

Release notes:

Initial release of the Julia port of the original Matlab [Active Set Pursuit implementation](https://github.com/MPF-Optimization-Laboratory/asp).

- blah

**Comment by mpf** [comment]
@JuliaRegistrator register

Release notes:

Initial release of the Julia port of the original Matlab [Active Set Pursuit implementation](https://github.com/MPF-Optimization-Laboratory/asp).

**Comment by cortner** [comment]
@JuliaRegistrator register
